// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Docker.Registry.OpenApiClient.V2.Item.Blobs;
using Soenneker.Docker.Registry.OpenApiClient.V2.Item.Manifests;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Docker.Registry.OpenApiClient.V2.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\{name}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithNameItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The blobs property</summary>
        public global::Soenneker.Docker.Registry.OpenApiClient.V2.Item.Blobs.BlobsRequestBuilder Blobs
        {
            get => new global::Soenneker.Docker.Registry.OpenApiClient.V2.Item.Blobs.BlobsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The manifests property</summary>
        public global::Soenneker.Docker.Registry.OpenApiClient.V2.Item.Manifests.ManifestsRequestBuilder Manifests
        {
            get => new global::Soenneker.Docker.Registry.OpenApiClient.V2.Item.Manifests.ManifestsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Docker.Registry.OpenApiClient.V2.Item.WithNameItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithNameItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/{name}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Docker.Registry.OpenApiClient.V2.Item.WithNameItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithNameItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/{name}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
