// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Docker.Registry.OpenApiClient.V2.Item.Blobs.Uploads.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Docker.Registry.OpenApiClient.V2.Item.Blobs.Uploads
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\{name}\blobs\uploads
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UploadsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Docker.Registry.OpenApiClient.v2.item.blobs.uploads.item collection</summary>
        /// <param name="position">Upload session UUID</param>
        /// <returns>A <see cref="global::Soenneker.Docker.Registry.OpenApiClient.V2.Item.Blobs.Uploads.Item.WithUuItemRequestBuilder"/></returns>
        public global::Soenneker.Docker.Registry.OpenApiClient.V2.Item.Blobs.Uploads.Item.WithUuItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("uuid", position);
                return new global::Soenneker.Docker.Registry.OpenApiClient.V2.Item.Blobs.Uploads.Item.WithUuItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Docker.Registry.OpenApiClient.V2.Item.Blobs.Uploads.UploadsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UploadsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/{name}/blobs/uploads{?from*,mount*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Docker.Registry.OpenApiClient.V2.Item.Blobs.Uploads.UploadsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UploadsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/{name}/blobs/uploads{?from*,mount*}", rawUrl)
        {
        }
        /// <summary>
        /// Initiate an upload session for a blob (layer or config) in a repository.This is the first step in uploading a blob. It returns a `Location` URL where the blob can be uploaded using `PATCH` (chunked) or `PUT` (monolithic).Instead of uploading a blob, a client may attempt to mount a blob from another repository (if it has read access) by including the `mount` and `from` query parameters.If successful, the registry responds with `201 Created` and the blob is reused without re-upload.If the mount fails, the upload proceeds as usual and returns a `202 Accepted`.You must authenticate with `push` access to the target repository.
        /// </summary>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task PostAsync(Action<RequestConfiguration<global::Soenneker.Docker.Registry.OpenApiClient.V2.Item.Blobs.Uploads.UploadsRequestBuilder.UploadsRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task PostAsync(Action<RequestConfiguration<global::Soenneker.Docker.Registry.OpenApiClient.V2.Item.Blobs.Uploads.UploadsRequestBuilder.UploadsRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPostRequestInformation(requestConfiguration);
            await RequestAdapter.SendNoContentAsync(requestInfo, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Initiate an upload session for a blob (layer or config) in a repository.This is the first step in uploading a blob. It returns a `Location` URL where the blob can be uploaded using `PATCH` (chunked) or `PUT` (monolithic).Instead of uploading a blob, a client may attempt to mount a blob from another repository (if it has read access) by including the `mount` and `from` query parameters.If successful, the registry responds with `201 Created` and the blob is reused without re-upload.If the mount fails, the upload proceeds as usual and returns a `202 Accepted`.You must authenticate with `push` access to the target repository.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<global::Soenneker.Docker.Registry.OpenApiClient.V2.Item.Blobs.Uploads.UploadsRequestBuilder.UploadsRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<global::Soenneker.Docker.Registry.OpenApiClient.V2.Item.Blobs.Uploads.UploadsRequestBuilder.UploadsRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Docker.Registry.OpenApiClient.V2.Item.Blobs.Uploads.UploadsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Docker.Registry.OpenApiClient.V2.Item.Blobs.Uploads.UploadsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Docker.Registry.OpenApiClient.V2.Item.Blobs.Uploads.UploadsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Initiate an upload session for a blob (layer or config) in a repository.This is the first step in uploading a blob. It returns a `Location` URL where the blob can be uploaded using `PATCH` (chunked) or `PUT` (monolithic).Instead of uploading a blob, a client may attempt to mount a blob from another repository (if it has read access) by including the `mount` and `from` query parameters.If successful, the registry responds with `201 Created` and the blob is reused without re-upload.If the mount fails, the upload proceeds as usual and returns a `202 Accepted`.You must authenticate with `push` access to the target repository.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class UploadsRequestBuilderPostQueryParameters 
        {
            /// <summary>Source repository to mount the blob from</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("from")]
            public string? From { get; set; }
#nullable restore
#else
            [QueryParameter("from")]
            public string From { get; set; }
#endif
            /// <summary>Digest of the blob to mount from another repository</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("mount")]
            public string? Mount { get; set; }
#nullable restore
#else
            [QueryParameter("mount")]
            public string Mount { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
