// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Docker.Registry.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetImageManifest200DockerDistributionManifestV2JsonResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The config property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Docker.Registry.OpenApiClient.Models.GetImageManifest200DockerDistributionManifestV2JsonResponseConfig? Config { get; set; }
#nullable restore
#else
        public global::Soenneker.Docker.Registry.OpenApiClient.Models.GetImageManifest200DockerDistributionManifestV2JsonResponseConfig Config { get; set; }
#endif
        /// <summary>The layers property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Docker.Registry.OpenApiClient.Models.GetImageManifest200DockerDistributionManifestV2JsonResponseLayersItem>? Layers { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Docker.Registry.OpenApiClient.Models.GetImageManifest200DockerDistributionManifestV2JsonResponseLayersItem> Layers { get; set; }
#endif
        /// <summary>The mediaType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MediaType { get; set; }
#nullable restore
#else
        public string MediaType { get; set; }
#endif
        /// <summary>The schemaVersion property</summary>
        public int? SchemaVersion { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Docker.Registry.OpenApiClient.Models.GetImageManifest200DockerDistributionManifestV2JsonResponse"/> and sets the default values.
        /// </summary>
        public GetImageManifest200DockerDistributionManifestV2JsonResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Docker.Registry.OpenApiClient.Models.GetImageManifest200DockerDistributionManifestV2JsonResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Docker.Registry.OpenApiClient.Models.GetImageManifest200DockerDistributionManifestV2JsonResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Docker.Registry.OpenApiClient.Models.GetImageManifest200DockerDistributionManifestV2JsonResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "config", n => { Config = n.GetObjectValue<global::Soenneker.Docker.Registry.OpenApiClient.Models.GetImageManifest200DockerDistributionManifestV2JsonResponseConfig>(global::Soenneker.Docker.Registry.OpenApiClient.Models.GetImageManifest200DockerDistributionManifestV2JsonResponseConfig.CreateFromDiscriminatorValue); } },
                { "layers", n => { Layers = n.GetCollectionOfObjectValues<global::Soenneker.Docker.Registry.OpenApiClient.Models.GetImageManifest200DockerDistributionManifestV2JsonResponseLayersItem>(global::Soenneker.Docker.Registry.OpenApiClient.Models.GetImageManifest200DockerDistributionManifestV2JsonResponseLayersItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "mediaType", n => { MediaType = n.GetStringValue(); } },
                { "schemaVersion", n => { SchemaVersion = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Docker.Registry.OpenApiClient.Models.GetImageManifest200DockerDistributionManifestV2JsonResponseConfig>("config", Config);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Docker.Registry.OpenApiClient.Models.GetImageManifest200DockerDistributionManifestV2JsonResponseLayersItem>("layers", Layers);
            writer.WriteStringValue("mediaType", MediaType);
            writer.WriteIntValue("schemaVersion", SchemaVersion);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
