// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Docker.Registry.OpenApiClient.V2.Item.Blobs.Item;
using Soenneker.Docker.Registry.OpenApiClient.V2.Item.Blobs.Uploads;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Docker.Registry.OpenApiClient.V2.Item.Blobs
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\{name}\blobs
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BlobsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The uploads property</summary>
        public global::Soenneker.Docker.Registry.OpenApiClient.V2.Item.Blobs.Uploads.UploadsRequestBuilder Uploads
        {
            get => new global::Soenneker.Docker.Registry.OpenApiClient.V2.Item.Blobs.Uploads.UploadsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Soenneker.Docker.Registry.OpenApiClient.v2.item.blobs.item collection</summary>
        /// <param name="position">Digest of the blob</param>
        /// <returns>A <see cref="global::Soenneker.Docker.Registry.OpenApiClient.V2.Item.Blobs.Item.WithDigestItemRequestBuilder"/></returns>
        public global::Soenneker.Docker.Registry.OpenApiClient.V2.Item.Blobs.Item.WithDigestItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("digest", position);
                return new global::Soenneker.Docker.Registry.OpenApiClient.V2.Item.Blobs.Item.WithDigestItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Docker.Registry.OpenApiClient.V2.Item.Blobs.BlobsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BlobsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/{name}/blobs", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Docker.Registry.OpenApiClient.V2.Item.Blobs.BlobsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BlobsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/{name}/blobs", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
