// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Docker.Registry.OpenApiClient.V2.Item.Manifests.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Docker.Registry.OpenApiClient.V2.Item.Manifests
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\{name}\manifests
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ManifestsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Docker.Registry.OpenApiClient.v2.item.manifests.item collection</summary>
        /// <param name="position">Tag or digest of the target manifest</param>
        /// <returns>A <see cref="global::Soenneker.Docker.Registry.OpenApiClient.V2.Item.Manifests.Item.WithReferenceItemRequestBuilder"/></returns>
        public global::Soenneker.Docker.Registry.OpenApiClient.V2.Item.Manifests.Item.WithReferenceItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("reference", position);
                return new global::Soenneker.Docker.Registry.OpenApiClient.V2.Item.Manifests.Item.WithReferenceItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Docker.Registry.OpenApiClient.V2.Item.Manifests.ManifestsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ManifestsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/{name}/manifests", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Docker.Registry.OpenApiClient.V2.Item.Manifests.ManifestsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ManifestsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/{name}/manifests", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
